name: Go Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install git-chglog
        run: |
          curl -s https://api.github.com/repos/git-chglog/git-chglog/releases/latest \
          | grep "browser_download_url.*linux_amd64.tar.gz" \
          | cut -d '"' -f 4 \
          | wget -qi - \
          && tar -xzf git-chglog*linux_amd64.tar.gz \
          && sudo mv git-chglog /usr/local/bin/

      - name: Generate Changelog
        run: git-chglog $(git describe --tags --abbrev=0)..HEAD > CHANGELOG.md

      - name: Run unit tests
        run: go test -v ./...

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/my-lib-linux-amd64
          GOOS=darwin GOARCH=arm64 go build -o build/my-lib-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o build/my-lib-windows-amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
